name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: echo "Hello, World!"

    - name: Jenkins Pipeline
      uses: appleboy/jenkins-action@master
      with:
        url: 'http://localhost:8080/'
        user: ${{ secrets.JENKINS_USERNAME }}
        token: ${{ secrets.JENKINS_TOKEN }}
        job: 'Teste'
