name: My Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install

    - name: Build app
      run: |
        npm run build

    - name: Test app
      run: |
        npm test

    - name: Jenkins Pipeline
      uses: appleboy/jenkins-action@master
      with:
        url: 'http://localhost:8080/'
        user: ${{ secrets.JENKINS_USERNAME }}
        token: ${{ secrets.JENKINS_TOKEN }}
        job: 'Teste'
